import { Layout, Menu } from 'antd';
import Head from 'next/head';

const {
  Header, Footer, Content,
} = Layout;

function Home() {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className="layout">
        <Header>
          <div className="logo" />
          <Menu theme="dark" mode="horizontal" defaultSelectedKeys={['2']}>
            {new Array(7).fill(null).map((_, index) => {
              const key = index + 1;
              return <Menu.Item key={key}>{`nav ${key}`}</Menu.Item>;
            })}
          </Menu>
        </Header>
        <Content style={{ padding: '0 50px' }}>
          <div />
        </Content>
      </Layout>

      <Footer style={{ textAlign: 'center' }}>
        <a
          href="https://sena.omg.lol"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          {' '}
          <span>
            Sena Aji
          </span>
        </a>
      </Footer>
    </>
  );
}

export default Home;
